window.OSANPO_DATA = {
  siteInfo: {
    lastUpdated: "2026-07-27",
    informationCheckedAt: "",
    fieldResearch: false,
    publicInfoBased: true,
    aiAssisted: true,
    expansionMessage: "東京40エリアを順次取材・拡充しています。",
    publishedAreaCount: 3,
    plannedAreaCount: 37,
  },
  images: {
    hero: "assets/images/hero/hero-tokyo-walk.webp",
    areaKoenji: "assets/images/areas/area-koenji.webp",
    areaKichijoji: "assets/images/areas/area-kichijoji.webp",
    areaAsakusa: "assets/images/areas/area-asakusa.webp",
    courseKoenji: "assets/images/courses/course-koenji.webp",
    courseKichijoji: "assets/images/courses/course-kichijoji.webp",
    courseAsakusa: "assets/images/courses/course-asakusa.webp",
    spotKoenjiJunjo: "assets/images/spots/spot-koenji-junjo.webp",
    spotInokashiraPark: "assets/images/spots/spot-inokashira-park.webp",
    spotSensoji: "assets/images/spots/spot-sensoji.webp",
    spotKoenjiHikawa: "assets/images/spots/spot-koenji-hikawa.webp",
    spotKichijojiArtMuseum: "assets/images/spots/spot-kichijoji-art-museum.webp",
    spotKappabashi: "assets/images/spots/spot-kappabashi.webp",
    storyKoenjiShoppingStreets: "assets/images/stories/story-koenji-shopping-streets.webp",
    storyInokashiraShortWalk: "assets/images/stories/story-inokashira-short-walk.webp",
    storyAsakusaFirstHour: "assets/images/stories/story-asakusa-first-hour.webp",
    eventKagurazakaFestival: "assets/images/events/event-kagurazaka-festival.webp",
    eventShinjukuEisa: "assets/images/events/event-shinjuku-eisa.webp",
    eventSumidagawaFireworks: "assets/images/events/event-sumidagawa-fireworks.webp",
    eventKoganeiAwaodori: "assets/images/events/event-koganei-awaodori.webp",
  },
  areas: [
    {
      id: "koenji",
      name: "高円寺",
      ward: "杉並区",
      lead: "古着と音楽、商店街と生活の路地が隣り合う街。",
      description: "北口の商店街から南口のアーケードまで、歩く方向で表情が変わります。短時間でも寄り道が生まれやすい街です。",
      image: "areaKoenji",
      imageAlt: "高円寺の商店街と路地を表現したイメージ",
      tags: ["古着", "商店街", "一人散歩"],
      stations: ["高円寺駅", "新高円寺駅"],
      budget: "1,000〜3,000円",
      duration: "2〜4時間",
      mapQuery: "高円寺駅",
      publicationStatus: "基本ガイド",
      fieldResearch: false,
      informationCheckedAt: "",
      officialSources: [
        { label: "高円寺純情商店街", url: "https://www.kouenji.or.jp/" },
        { label: "高円寺氷川神社・気象神社", url: "https://koenji-hikawa.com/" },
      ],
      needsFieldCheck: "コースの歩きやすさ、休憩候補、現地の最新状況",
    },
    {
      id: "kichijoji",
      name: "吉祥寺",
      ward: "武蔵野市",
      lead: "公園、水辺、商店街が近い距離にまとまる街。",
      description: "井の頭公園で緑を楽しんだ後、中道通りや駅前の商店街へ。自然と買い物を無理なく組み合わせられます。",
      image: "areaKichijoji",
      imageAlt: "吉祥寺の緑と水辺の街歩きを表現したイメージ",
      tags: ["公園", "カフェ", "デート"],
      stations: ["吉祥寺駅"],
      budget: "1,500〜4,000円",
      duration: "2〜5時間",
      mapQuery: "吉祥寺駅 井の頭恩賜公園",
      publicationStatus: "基本ガイド",
      fieldResearch: false,
      informationCheckedAt: "",
      officialSources: [
        { label: "井の頭恩賜公園", url: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/" },
        { label: "武蔵野市立吉祥寺美術館", url: "https://www.musashino.or.jp/museum/" },
      ],
      needsFieldCheck: "コースの歩きやすさ、休憩候補、現地の最新状況",
    },
    {
      id: "asakusa",
      name: "浅草",
      ward: "台東区",
      lead: "門前町の歴史と、道具街・水辺まで楽しめる下町。",
      description: "雷門周辺だけで終わらせず、浅草寺の西側やかっぱ橋まで歩くと、観光地と生活の街の両方が見えてきます。",
      image: "areaAsakusa",
      imageAlt: "浅草の門前町と下町の街並みを表現したイメージ",
      tags: ["歴史", "建築", "下町"],
      stations: ["浅草駅", "田原町駅"],
      budget: "1,000〜4,000円",
      duration: "2〜5時間",
      mapQuery: "浅草寺 かっぱ橋道具街",
      publicationStatus: "基本ガイド",
      fieldResearch: false,
      informationCheckedAt: "",
      officialSources: [
        { label: "浅草寺", url: "https://www.senso-ji.jp/" },
        { label: "かっぱ橋道具街", url: "https://www.kappabashi.or.jp/" },
      ],
      needsFieldCheck: "コースの歩きやすさ、休憩候補、現地の最新状況",
    },
  ],
  courses: [
    {
      id: "koenji-first",
      areaId: "koenji",
      title: "初めての高円寺：商店街と路地を2時間で歩く",
      summary: "北口の純情商店街から気象神社を経て、南口のパル・ルック商店街へ抜ける入門コース。",
      distance: "約1.8km",
      duration: "約2時間",
      budget: "1,000〜2,500円",
      audience: "一人・友人",
      image: "courseKoenji",
      imageAlt: "高円寺駅北口から南口へ続く商店街と路地を表現したイメージ",
      stops: [
        { name: "JR高円寺駅 北口", category: "START", query: "JR高円寺駅 北口" },
        { name: "高円寺純情商店街", category: "商店街", query: "高円寺純情商店街" },
        { name: "小杉湯", category: "銭湯", query: "小杉湯 高円寺" },
        { name: "高円寺氷川神社・気象神社", category: "神社", query: "高円寺氷川神社 気象神社" },
        { name: "高円寺パル商店街", category: "商店街", query: "高円寺パル商店街" },
        { name: "高円寺ルック商店街", category: "商店街", query: "高円寺ルック商店街" },
        { name: "新高円寺駅", category: "GOAL", query: "新高円寺駅" },
      ],
    },
    {
      id: "kichijoji-park",
      areaId: "kichijoji",
      title: "吉祥寺：井の頭公園と商店街を半日でつなぐ",
      summary: "公園を短く歩き、御殿山から中道通り、ハモニカ横丁へ戻る半日コース。",
      distance: "約3.2km",
      duration: "約3時間",
      budget: "1,500〜4,000円",
      audience: "一人・デート",
      image: "courseKichijoji",
      imageAlt: "井の頭公園の水辺と街を巡る吉祥寺コースを表現したイメージ",
      stops: [
        { name: "吉祥寺駅 公園口", category: "START", query: "吉祥寺駅 公園口" },
        { name: "七井橋", category: "水辺", query: "七井橋 井の頭公園" },
        { name: "井の頭弁財天", category: "寺社", query: "井の頭弁財天" },
        { name: "御殿山通り", category: "街路", query: "御殿山通り 吉祥寺" },
        { name: "中道通り", category: "商店街", query: "中道通り 吉祥寺" },
        { name: "吉祥寺美術館", category: "文化", query: "武蔵野市立吉祥寺美術館" },
        { name: "ハモニカ横丁", category: "GOAL", query: "ハモニカ横丁" },
      ],
    },
    {
      id: "asakusa-history",
      areaId: "asakusa",
      title: "浅草：雷門からかっぱ橋へ、門前町の歴史を歩く",
      summary: "雷門・仲見世・浅草寺を押さえ、西側の商店街とかっぱ橋道具街へ抜けます。",
      distance: "約2.4km",
      duration: "約2時間30分",
      budget: "1,000〜3,500円",
      audience: "一人・家族・観光",
      image: "courseAsakusa",
      imageAlt: "浅草の門前町と寺社を巡る散歩コースを表現したイメージ",
      stops: [
        { name: "浅草文化観光センター", category: "START", query: "浅草文化観光センター" },
        { name: "雷門", category: "歴史", query: "雷門" },
        { name: "仲見世通り", category: "商店街", query: "仲見世通り" },
        { name: "浅草寺", category: "寺社", query: "浅草寺" },
        { name: "西参道商店街", category: "商店街", query: "浅草西参道商店街" },
        { name: "かっぱ橋本通り", category: "街路", query: "かっぱ橋本通り" },
        { name: "かっぱ橋道具街", category: "買い物", query: "かっぱ橋道具街" },
        { name: "田原町駅", category: "GOAL", query: "田原町駅" },
      ],
    },
  ],
  spots: [
    {
      id: "koenji-junjo",
      areaId: "koenji",
      name: "高円寺純情商店街",
      category: "商店街",
      excerpt: "高円寺駅北口から始まる商店街。北側散歩の導入として歩きやすい場所です。",
      image: "spotKoenjiJunjo",
      imageAlt: "高円寺の低層商店街と路地を表現したイメージ",
      mapQuery: "高円寺純情商店街",
      officialUrl: "https://www.kouenji.or.jp/",
    },
    {
      id: "koenji-hikawa",
      areaId: "koenji",
      name: "高円寺氷川神社・気象神社",
      category: "神社",
      excerpt: "高円寺駅南側で、商店街歩きに歴史の立ち寄りを加えられる場所です。",
      image: "spotKoenjiHikawa",
      imageAlt: "高円寺氷川神社・気象神社の鳥居と境内を表現したイメージ",
      mapQuery: "高円寺氷川神社 気象神社",
      officialUrl: "https://koenji-hikawa.com/",
    },
    {
      id: "inokashira-park",
      areaId: "kichijoji",
      name: "井の頭恩賜公園",
      category: "公園",
      excerpt: "池、水辺、木陰を楽しめる吉祥寺散歩の中心。短時間でも景色を変えやすい公園です。",
      image: "spotInokashiraPark",
      imageAlt: "井の頭恩賜公園の緑と水辺を表現したイメージ",
      mapQuery: "井の頭恩賜公園",
      officialUrl: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/",
    },
    {
      id: "kichijoji-art-museum",
      areaId: "kichijoji",
      name: "武蔵野市立吉祥寺美術館",
      category: "文化施設",
      excerpt: "駅近くで雨天時にも組み込みやすい文化施設。商店街散歩の休憩地点にもなります。",
      image: "spotKichijojiArtMuseum",
      imageAlt: "吉祥寺の街中にある都市型美術館を表現したイメージ",
      mapQuery: "武蔵野市立吉祥寺美術館",
      officialUrl: "https://www.musashino.or.jp/museum/",
    },
    {
      id: "sensoji",
      areaId: "asakusa",
      name: "浅草寺周辺",
      category: "寺社・歴史",
      excerpt: "浅草の歴史散歩の中心。朝と昼で人の流れが大きく変わるため、時間帯選びも楽しみの一つです。",
      image: "spotSensoji",
      imageAlt: "浅草寺周辺の門前町と寺院建築を表現したイメージ",
      mapQuery: "浅草寺",
      officialUrl: "https://www.senso-ji.jp/",
    },
    {
      id: "kappabashi",
      areaId: "asakusa",
      name: "かっぱ橋道具街",
      category: "商店街",
      excerpt: "調理道具や器の専門店が続く通り。浅草寺周辺から少し歩くことで街の表情が変わります。",
      image: "spotKappabashi",
      imageAlt: "かっぱ橋道具街の調理器具店が並ぶ通りを表現したイメージ",
      mapQuery: "かっぱ橋道具街",
      officialUrl: "https://www.kappabashi.or.jp/",
    },
  ],
  stories: [
    {
      id: "koenji-shopping-streets",
      areaId: "koenji",
      category: "街の読み物",
      readTime: "約4分",
      title: "高円寺は、商店街を一本に決めないほうが面白い。",
      excerpt: "純情商店街からパル、ルックへ。駅の北と南をつなぐと、買い物の街と生活の街が同時に見えてきます。",
      image: "storyKoenjiShoppingStreets",
      imageAlt: "高円寺の複数の商店街と路地を歩き継ぐ読み物を表現したイメージ",
      intro: "高円寺の面白さは、一つの有名スポットを目指すことより、商店街の切り替わりを歩いて確かめることにあります。",
      sections: [
        { heading: "北口は、散歩の速度を落としやすい", body: "駅を出て純情商店街へ入ると、飲食店や生活に近い店が短い間隔で並びます。目的を一つに絞らず、気になった通りを一本だけ横へ入るのが向いています。" },
        { heading: "南口では、アーケードが街をつなぐ", body: "氷川神社を経由して南へ回ると、パル商店街とルック商店街が連続します。雨や強い日差しを避けながら歩きやすい区間です。" },
        { heading: "二つの駅を結ぶと、帰り方も選べる", body: "高円寺駅へ戻るだけでなく、新高円寺駅をゴールにすると同じ道を引き返さずに済みます。体力に合わせて途中で地下鉄へ切り替えられるのも利点です。" },
      ],
    },
    {
      id: "inokashira-short-walk",
      areaId: "kichijoji",
      category: "公園の読み物",
      readTime: "約4分",
      title: "井の頭公園は、一周しなくても十分に深い。",
      excerpt: "七井橋、井の頭池、弁財天。駅から近い公園を「短く歩いて、長く眺める」半日へ。",
      image: "storyInokashiraShortWalk",
      imageAlt: "井の頭公園の橋、水辺、木陰を短く巡る読み物を表現したイメージ",
      intro: "井の頭公園は広いからこそ、全部を見るより、橋・水辺・木陰を一つずつ選ぶ方が満足しやすい場所です。",
      sections: [
        { heading: "最初に七井橋で景色をつかむ", body: "公園へ下りたら、まず橋の上から池の広がりを確認します。歩く範囲を決める目印にもなります。" },
        { heading: "池を一周しない選択", body: "混雑や暑さが気になる日は、弁財天周辺までに絞り、木陰で過ごす時間を増やすのがおすすめです。" },
        { heading: "街へ戻る道も散歩に含める", body: "御殿山や中道通りを経由すれば、公園の緑から小さな店が続く街へ自然に切り替わります。" },
      ],
    },
    {
      id: "asakusa-first-hour",
      areaId: "asakusa",
      category: "街の読み物",
      readTime: "約4分",
      title: "浅草の最初の1時間は、雷門の向かいから始める。",
      excerpt: "浅草文化観光センターで、地図、混雑、休憩場所を確認してから門前町へ入る。",
      image: "storyAsakusaFirstHour",
      imageAlt: "浅草の街を見渡してから門前町へ入る読み物を表現したイメージ",
      intro: "浅草は最初から人の流れに乗るより、少し高い場所から街の方向を確認すると歩きやすくなります。",
      sections: [
        { heading: "最初に情報を集める", body: "浅草文化観光センターで地図や当日の案内を確認しておくと、雷門周辺の混雑に合わせて進路を変えやすくなります。" },
        { heading: "仲見世は目的地ではなく通過点", body: "仲見世を抜けて浅草寺へ進んだ後、西側の通りへ回ると、門前町の異なる表情が見えてきます。" },
        { heading: "最後は道具街へ", body: "かっぱ橋まで歩くと、寺社中心の景色から専門店の街へ変化します。田原町駅をゴールにすれば帰路も分かりやすくなります。" },
      ],
    },
  ],
  events: [
    {
      id: "kagurazaka-festival-2026",
      title: "第52回 神楽坂まつり",
      area: "神楽坂",
      start: "2026-07-22T17:00:00+09:00",
      end: "2026-07-25T21:00:00+09:00",
      venue: "神楽坂通り周辺",
      price: "観覧無料",
      status: "",
      image: "eventKagurazakaFestival",
      imageAlt: "提灯と屋台が並ぶ神楽坂の夏祭りを表現したイメージ",
      officialUrl: "https://www.kagurazaka.in/kagurazaka_festival/52th/",
      mapQuery: "神楽坂通り",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
    {
      id: "shinjuku-eisa-2026",
      title: "第23回 新宿エイサーまつり",
      area: "新宿",
      start: "2026-07-25T12:00:00+09:00",
      end: "2026-07-25T20:00:00+09:00",
      venue: "新宿駅東口周辺",
      price: "観覧無料",
      status: "",
      image: "eventShinjukuEisa",
      imageAlt: "新宿の街路で行われるエイサー演舞を表現したイメージ",
      officialUrl: "https://www.shinjuku-eisa.com/",
      mapQuery: "新宿駅 東口",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
    {
      id: "sumidagawa-fireworks-2026",
      title: "第49回 隅田川花火大会",
      area: "浅草・墨田",
      start: "2026-07-25T19:00:00+09:00",
      end: "2026-07-25T20:30:00+09:00",
      venue: "隅田川 第一・第二会場",
      price: "観覧無料（一部有料席）",
      status: "",
      image: "eventSumidagawaFireworks",
      imageAlt: "隅田川の水面と夜空の花火を表現したイメージ",
      officialUrl: "https://www.sumidagawa-hanabi.com/",
      mapQuery: "隅田川花火大会 第一会場",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
    {
      id: "koganei-awaodori-2026",
      title: "第48回 小金井阿波おどり",
      area: "小金井",
      start: "2026-07-25T18:00:00+09:00",
      end: "2026-07-26T21:00:00+09:00",
      venue: "武蔵小金井駅周辺",
      price: "観覧無料",
      status: "",
      image: "eventKoganeiAwaodori",
      imageAlt: "武蔵小金井駅周辺の阿波おどりを表現したイメージ",
      officialUrl: "https://koganeiawaodori.jp/",
      mapQuery: "武蔵小金井駅",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
  ],
};
