export const siteData = {
  siteInfo: {
    lastUpdated: "2026-07-27",
    informationCheckedAt: "",
    fieldResearch: false,
    publicInfoBased: true,
    aiAssisted: true,
    expansionMessage: "東京40エリアへの拡充を予定しています。公開情報の確認と現地取材を順次進めます。",
    publishedAreaCount: 3,
    plannedAreaCount: 37,
  },
  images: {
    hero: "assets/images/hero/hero-tokyo-walk.webp",
    areaKoenji: "assets/images/areas/area-koenji.webp",
    areaKichijoji: "assets/images/areas/area-kichijoji.webp",
    areaAsakusa: "assets/images/areas/area-asakusa.webp",
    courseKoenji: "assets/images/courses/course-koenji.webp",
    courseKichijoji: "assets/images/courses/course-kichijoji.webp",
    courseAsakusa: "assets/images/courses/course-asakusa.webp",
    spotKoenjiJunjo: "assets/images/spots/spot-koenji-junjo.webp",
    spotInokashiraPark: "assets/images/spots/spot-inokashira-park.webp",
    spotSensoji: "assets/images/spots/spot-sensoji.webp",
    spotKoenjiHikawa: "assets/images/spots/spot-koenji-hikawa.webp",
    spotKichijojiArtMuseum: "assets/images/spots/spot-kichijoji-art-museum.webp",
    spotKappabashi: "assets/images/spots/spot-kappabashi.webp",
    storyKoenjiShoppingStreets: "assets/images/stories/story-koenji-shopping-streets.webp",
    storyInokashiraShortWalk: "assets/images/stories/story-inokashira-short-walk.webp",
    storyAsakusaFirstHour: "assets/images/stories/story-asakusa-first-hour.webp",
    eventKagurazakaFestival: "assets/images/events/event-kagurazaka-festival.webp",
    eventShinjukuEisa: "assets/images/events/event-shinjuku-eisa.webp",
    eventSumidagawaFireworks: "assets/images/events/event-sumidagawa-fireworks.webp",
    eventKoganeiAwaodori: "assets/images/events/event-koganei-awaodori.webp",
  },
  areas: [
    {
      id: "koenji",
      name: "高円寺",
      ward: "杉並区",
      lead: "古着と音楽、商店街と生活の路地が隣り合う街。",
      description: "北口の商店街から南口のアーケードまで、歩く方向で表情が変わります。短時間でも寄り道が生まれやすい街です。",
      image: "areaKoenji",
      imageAlt: "高円寺の商店街と路地を表現したイメージ",
      tags: ["古着", "商店街", "一人散歩"],
      stations: ["高円寺駅", "新高円寺駅"],
      budget: "1,000〜3,000円",
      duration: "2〜4時間",
      mapQuery: "高円寺駅",
      publicationStatus: "基本ガイド",
      fieldResearch: false,
      informationCheckedAt: "",
      officialSources: [
        { label: "高円寺純情商店街", url: "https://www.kouenji.or.jp/" },
        { label: "高円寺氷川神社・気象神社", url: "https://koenji-hikawa.com/" },
      ],
      needsFieldCheck: "コースの歩きやすさ、休憩候補、現地の最新状況",
    },
    {
      id: "kichijoji",
      name: "吉祥寺",
      ward: "武蔵野市",
      lead: "公園、水辺、商店街が近い距離にまとまる街。",
      description: "井の頭公園で緑を楽しんだ後、中道通りや駅前の商店街へ。自然と買い物を無理なく組み合わせられます。",
      image: "areaKichijoji",
      imageAlt: "吉祥寺の緑と水辺の街歩きを表現したイメージ",
      tags: ["公園", "カフェ", "デート"],
      stations: ["吉祥寺駅"],
      budget: "1,500〜4,000円",
      duration: "2〜5時間",
      mapQuery: "吉祥寺駅 井の頭恩賜公園",
      publicationStatus: "基本ガイド",
      fieldResearch: false,
      informationCheckedAt: "",
      officialSources: [
        { label: "井の頭恩賜公園", url: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/" },
        { label: "武蔵野市立吉祥寺美術館", url: "https://www.musashino.or.jp/museum/" },
      ],
      needsFieldCheck: "コースの歩きやすさ、休憩候補、現地の最新状況",
    },
    {
      id: "asakusa",
      name: "浅草",
      ward: "台東区",
      lead: "門前町の歴史と、道具街・水辺まで楽しめる下町。",
      description: "雷門周辺だけで終わらせず、浅草寺の西側やかっぱ橋まで歩くと、観光地と生活の街の両方が見えてきます。",
      image: "areaAsakusa",
      imageAlt: "浅草の門前町と下町の街並みを表現したイメージ",
      tags: ["歴史", "建築", "下町"],
      stations: ["浅草駅", "田原町駅"],
      budget: "1,000〜4,000円",
      duration: "2〜5時間",
      mapQuery: "浅草寺 かっぱ橋道具街",
      publicationStatus: "基本ガイド",
      fieldResearch: false,
      informationCheckedAt: "",
      officialSources: [
        { label: "浅草寺", url: "https://www.senso-ji.jp/" },
        { label: "かっぱ橋道具街", url: "https://www.kappabashi.or.jp/" },
      ],
      needsFieldCheck: "コースの歩きやすさ、休憩候補、現地の最新状況",
    },
  ],
  courses: [
    {
      id: "koenji-first",
      areaId: "koenji",
      title: "初めての高円寺：商店街と路地を2時間で歩く",
      summary: "北口の純情商店街から気象神社を経て、南口のパル・ルック商店街へ抜ける入門コース。",
      distance: "約1.8km",
      duration: "約2時間",
      budget: "1,000〜2,500円",
      audience: "一人・友人",
      durationMinutes: 120,
      budgetMaxYen: 2500,
      audienceKeys: ["solo", "friends"],
      moodKeys: ["shopping", "vintage"],
      image: "courseKoenji",
      imageAlt: "高円寺駅北口から南口へ続く商店街と路地を表現したイメージ",
      stops: [
        { name: "JR高円寺駅 北口", category: "START", query: "JR高円寺駅 北口" },
        { name: "高円寺純情商店街", category: "商店街", query: "高円寺純情商店街" },
        { name: "小杉湯", category: "銭湯", query: "小杉湯 高円寺" },
        { name: "高円寺氷川神社・気象神社", category: "神社", query: "高円寺氷川神社 気象神社" },
        { name: "高円寺パル商店街", category: "商店街", query: "高円寺パル商店街" },
        { name: "高円寺ルック商店街", category: "商店街", query: "高円寺ルック商店街" },
        { name: "新高円寺駅", category: "GOAL", query: "新高円寺駅" },
      ],
      routeStops: [
        { order: 1, name: "高円寺駅北口", query: "高円寺駅 北口 東京都杉並区", role: "start" },
        { order: 2, name: "高円寺純情商店街", query: "高円寺純情商店街 東京都杉並区", role: "stop" },
        { order: 3, name: "小杉湯", query: "小杉湯 東京都杉並区高円寺北", role: "stop" },
        { order: 4, name: "高円寺氷川神社・気象神社", query: "高円寺氷川神社 気象神社 東京都杉並区", role: "stop" },
        { order: 5, name: "高円寺パル商店街", query: "高円寺パル商店街 東京都杉並区", role: "stop" },
        { order: 6, name: "高円寺ルック商店街", query: "高円寺ルック商店街 東京都杉並区", role: "stop" },
        { order: 7, name: "新高円寺駅", query: "新高円寺駅 東京都杉並区", role: "goal" },
      ],
      routeSegments: [
        { id: "part-1", label: "前半", originStopOrder: 1, waypointStopOrders: [2, 3], destinationStopOrder: 4 },
        { id: "part-2", label: "後半", originStopOrder: 4, waypointStopOrders: [5, 6], destinationStopOrder: 7 },
      ],
      routeNotice: "Googleマップの徒歩経路は変更される場合があります。現地の案内と最新情報をご確認ください。",
    },
    {
      id: "kichijoji-park",
      areaId: "kichijoji",
      title: "吉祥寺：井の頭公園と商店街を半日でつなぐ",
      summary: "公園を短く歩き、御殿山から中道通り、ハモニカ横丁へ戻る半日コース。",
      distance: "約3.2km",
      duration: "約3時間",
      budget: "1,500〜4,000円",
      audience: "一人・デート",
      durationMinutes: 180,
      budgetMaxYen: 4000,
      audienceKeys: ["solo", "date"],
      moodKeys: ["nature", "cafe"],
      image: "courseKichijoji",
      imageAlt: "井の頭公園の水辺と街を巡る吉祥寺コースを表現したイメージ",
      stops: [
        { name: "吉祥寺駅 公園口", category: "START", query: "吉祥寺駅 公園口" },
        { name: "七井橋", category: "水辺", query: "七井橋 井の頭公園" },
        { name: "井の頭弁財天", category: "寺社", query: "井の頭弁財天" },
        { name: "御殿山通り", category: "街路", query: "御殿山通り 吉祥寺" },
        { name: "中道通り", category: "商店街", query: "中道通り 吉祥寺" },
        { name: "吉祥寺美術館", category: "文化", query: "武蔵野市立吉祥寺美術館" },
        { name: "ハモニカ横丁", category: "GOAL", query: "ハモニカ横丁" },
      ],
      routeStops: [
        { order: 1, name: "吉祥寺駅公園口", query: "吉祥寺駅 公園口 東京都武蔵野市", role: "start" },
        { order: 2, name: "七井橋", query: "七井橋 井の頭公園", role: "stop" },
        { order: 3, name: "井の頭弁財天", query: "井の頭弁財天 東京都三鷹市", role: "stop" },
        { order: 4, name: "御殿山通り", query: "御殿山通り 吉祥寺 東京都武蔵野市", role: "stop" },
        { order: 5, name: "中道通り", query: "中道通り 吉祥寺 東京都武蔵野市", role: "stop" },
        { order: 6, name: "武蔵野市立吉祥寺美術館", query: "武蔵野市立吉祥寺美術館", role: "stop" },
        { order: 7, name: "ハモニカ横丁", query: "ハモニカ横丁 吉祥寺 東京都武蔵野市", role: "goal" },
      ],
      routeSegments: [
        { id: "part-1", label: "前半", originStopOrder: 1, waypointStopOrders: [2, 3], destinationStopOrder: 4 },
        { id: "part-2", label: "後半", originStopOrder: 4, waypointStopOrders: [5, 6], destinationStopOrder: 7 },
      ],
      routeNotice: "Googleマップの徒歩経路は変更される場合があります。現地の案内と最新情報をご確認ください。",
    },
    {
      id: "asakusa-history",
      areaId: "asakusa",
      title: "浅草：雷門からかっぱ橋へ、門前町の歴史を歩く",
      summary: "雷門・仲見世・浅草寺を押さえ、西側の商店街とかっぱ橋道具街へ抜けます。",
      distance: "約2.4km",
      duration: "約2時間30分",
      budget: "1,000〜3,500円",
      audience: "一人・家族・観光",
      durationMinutes: 150,
      budgetMaxYen: 3500,
      audienceKeys: ["solo", "family", "sightseeing"],
      moodKeys: ["history", "shopping"],
      image: "courseAsakusa",
      imageAlt: "浅草の門前町と寺社を巡る散歩コースを表現したイメージ",
      stops: [
        { name: "浅草文化観光センター", category: "START", query: "浅草文化観光センター" },
        { name: "雷門", category: "歴史", query: "雷門" },
        { name: "仲見世通り", category: "商店街", query: "仲見世通り" },
        { name: "浅草寺", category: "寺社", query: "浅草寺" },
        { name: "西参道商店街", category: "商店街", query: "浅草西参道商店街" },
        { name: "かっぱ橋本通り", category: "街路", query: "かっぱ橋本通り" },
        { name: "かっぱ橋道具街", category: "買い物", query: "かっぱ橋道具街" },
        { name: "田原町駅", category: "GOAL", query: "田原町駅" },
      ],
      routeStops: [
        { order: 1, name: "浅草文化観光センター", query: "浅草文化観光センター 東京都台東区", role: "start" },
        { order: 2, name: "雷門", query: "雷門 浅草寺 東京都台東区", role: "stop" },
        { order: 3, name: "仲見世商店街", query: "仲見世商店街 東京都台東区", role: "stop" },
        { order: 4, name: "浅草寺", query: "浅草寺 東京都台東区", role: "stop" },
        { order: 5, name: "浅草西参道商店街", query: "浅草西参道商店街 東京都台東区", role: "stop" },
        { order: 6, name: "かっぱ橋本通り", query: "かっぱ橋本通り 東京都台東区", role: "stop" },
        { order: 7, name: "かっぱ橋道具街", query: "かっぱ橋道具街 東京都台東区", role: "stop" },
        { order: 8, name: "田原町駅", query: "田原町駅 東京都台東区", role: "goal" },
      ],
      routeSegments: [
        { id: "part-1", label: "前半", originStopOrder: 1, waypointStopOrders: [2, 3, 4], destinationStopOrder: 5 },
        { id: "part-2", label: "後半", originStopOrder: 5, waypointStopOrders: [6, 7], destinationStopOrder: 8 },
      ],
      routeNotice: "Googleマップの徒歩経路は変更される場合があります。現地の案内と最新情報をご確認ください。",
    },
  ],
  transitAccess: [
    {
      id: "koenji-arrival",
      courseId: "koenji-first",
      role: "arrival",
      roleLabel: "行き",
      stationName: "高円寺駅",
      stationCode: "JC07／JB06",
      routeConnection: "コースSTARTは高円寺駅北口です。",
      recommendedExit: "",
      exitVerified: false,
      mapQuery: "JR高円寺駅 東京都杉並区高円寺南4丁目",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      officialSources: [
        { label: "JR東日本 高円寺駅", url: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=663" },
        { label: "JR東日本 高円寺駅構内図・バリアフリー情報", url: "https://www.jreast.co.jp/estation/stations/663.html" },
      ],
      operators: [
        {
          name: "JR東日本",
          lines: ["中央線・青梅線・五日市線", "中央線・総武線各駅停車"],
          stationPageUrl: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=663",
          timetableUrl: "https://timetables.jreast.co.jp/timetable/list0663.html",
          stationMapUrl: "https://www.jreast.co.jp/estation/stations/663.html",
          barrierFreeUrl: "https://www.jreast.co.jp/estation/stations/663.html",
          operationInfoUrl: "https://traininfo.jreast.co.jp/train_info/kanto.aspx",
        },
      ],
      alternativeStations: [],
    },
    {
      id: "koenji-return",
      courseId: "koenji-first",
      role: "return",
      roleLabel: "帰り",
      stationName: "新高円寺駅",
      stationCode: "M03",
      routeConnection: "コースGOALが新高円寺駅です。",
      recommendedExit: "",
      exitVerified: false,
      mapQuery: "東京メトロ 新高円寺駅 東京都杉並区高円寺南2-20-1",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      officialSources: [
        { label: "東京メトロ 新高円寺駅", url: "https://www.tokyometro.jp/station/shin-koenji/index.html" },
        { label: "東京メトロ 新高円寺駅バリアフリー設備", url: "https://www.tokyometro.jp/station/shin-koenji/accessibility/index.html" },
      ],
      operators: [
        {
          name: "東京メトロ",
          lines: ["丸ノ内線"],
          stationPageUrl: "https://www.tokyometro.jp/station/shin-koenji/index.html",
          timetableUrl: "https://www.tokyometro.jp/station/shin-koenji/timetable/index.html",
          stationMapUrl: "https://www.tokyometro.jp/station/shin-koenji/index.html",
          barrierFreeUrl: "https://www.tokyometro.jp/station/shin-koenji/accessibility/index.html",
          operationInfoUrl: "https://www.tokyometro.jp/unkou/index.html",
        },
      ],
      alternativeStations: [],
    },
    {
      id: "kichijoji-arrival",
      courseId: "kichijoji-park",
      role: "arrival",
      roleLabel: "行き",
      stationName: "吉祥寺駅",
      stationCode: "JC11／JB02／IN17",
      routeConnection: "コースSTARTは吉祥寺駅公園口です。",
      recommendedExit: "",
      exitVerified: false,
      mapQuery: "吉祥寺駅 東京都武蔵野市吉祥寺南町1丁目",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      officialSources: [
        { label: "JR東日本 吉祥寺駅", url: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=596" },
        { label: "京王電鉄 吉祥寺駅", url: "https://www.keio.co.jp/train/station/in17_kichijoji/" },
      ],
      operators: [
        {
          name: "JR東日本",
          lines: ["中央線・青梅線・五日市線", "中央線・総武線各駅停車"],
          stationPageUrl: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=596",
          timetableUrl: "https://timetables.jreast.co.jp/timetable/list0596.html",
          stationMapUrl: "https://www.jreast.co.jp/estation/stations/596.html",
          barrierFreeUrl: "https://www.jreast.co.jp/estation/stations/596.html",
          operationInfoUrl: "https://traininfo.jreast.co.jp/train_info/kanto.aspx",
        },
        {
          name: "京王電鉄",
          lines: ["井の頭線"],
          stationPageUrl: "https://www.keio.co.jp/train/station/in17_kichijoji/",
          timetableUrl: "https://transfer-train.navitime.biz/keio/directions/timetable?direction=0&line=7&station=1556&target=weekday",
          stationMapUrl: "https://www.keio.co.jp/train/station/station_map/pdf/in17_kichijoji.pdf",
          barrierFreeUrl: "https://www.keio.co.jp/train/station/in17_kichijoji/",
          operationInfoUrl: "https://www.keio.co.jp/unkou/unkou_pc.html",
        },
      ],
      alternativeStations: [],
    },
    {
      id: "kichijoji-return",
      courseId: "kichijoji-park",
      role: "return",
      roleLabel: "帰り",
      stationName: "吉祥寺駅",
      stationCode: "JC11／JB02／IN17",
      routeConnection: "ハモニカ横丁付近のGOALから吉祥寺駅へ戻れます。",
      recommendedExit: "",
      exitVerified: false,
      mapQuery: "吉祥寺駅 東京都武蔵野市吉祥寺南町1丁目",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      officialSources: [
        { label: "JR東日本 吉祥寺駅", url: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=596" },
        { label: "京王電鉄 吉祥寺駅", url: "https://www.keio.co.jp/train/station/in17_kichijoji/" },
      ],
      operators: [
        {
          name: "JR東日本",
          lines: ["中央線・青梅線・五日市線", "中央線・総武線各駅停車"],
          stationPageUrl: "https://www.jreast.co.jp/estation/station/info.aspx?StationCd=596",
          timetableUrl: "https://timetables.jreast.co.jp/timetable/list0596.html",
          stationMapUrl: "https://www.jreast.co.jp/estation/stations/596.html",
          barrierFreeUrl: "https://www.jreast.co.jp/estation/stations/596.html",
          operationInfoUrl: "https://traininfo.jreast.co.jp/train_info/kanto.aspx",
        },
        {
          name: "京王電鉄",
          lines: ["井の頭線"],
          stationPageUrl: "https://www.keio.co.jp/train/station/in17_kichijoji/",
          timetableUrl: "https://transfer-train.navitime.biz/keio/directions/timetable?direction=0&line=7&station=1556&target=weekday",
          stationMapUrl: "https://www.keio.co.jp/train/station/station_map/pdf/in17_kichijoji.pdf",
          barrierFreeUrl: "https://www.keio.co.jp/train/station/in17_kichijoji/",
          operationInfoUrl: "https://www.keio.co.jp/unkou/unkou_pc.html",
        },
      ],
      alternativeStations: [],
    },
    {
      id: "asakusa-arrival",
      courseId: "asakusa-history",
      role: "arrival",
      roleLabel: "行き",
      stationName: "東京メトロ浅草駅",
      stationCode: "G19",
      routeConnection: "浅草文化観光センターがコースSTARTです。",
      recommendedExit: "",
      exitVerified: false,
      mapQuery: "東京メトロ 浅草駅 銀座線 東京都台東区浅草1-1-3",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      officialSources: [
        { label: "東京メトロ 浅草駅", url: "https://www.tokyometro.jp/station/asakusa/index.html" },
        { label: "東京メトロ 浅草駅バリアフリー設備", url: "https://www.tokyometro.jp/station/asakusa/accessibility/index.html" },
        { label: "東京都交通局 浅草駅", url: "https://www.kotsu.metro.tokyo.jp/subway/stations/asakusa.html" },
        { label: "東武鉄道 浅草駅", url: "https://www.tobu.co.jp/railway/guide/station/info/1102.html" },
        { label: "つくばエクスプレス 浅草駅", url: "https://www.mir.co.jp/route_map/asakusa/" },
      ],
      operators: [
        {
          name: "東京メトロ",
          lines: ["銀座線"],
          stationPageUrl: "https://www.tokyometro.jp/station/asakusa/index.html",
          timetableUrl: "https://www.tokyometro.jp/station/asakusa/timetable/index.html",
          stationMapUrl: "https://www.tokyometro.jp/station/asakusa/index.html",
          barrierFreeUrl: "https://www.tokyometro.jp/station/asakusa/accessibility/index.html",
          operationInfoUrl: "https://www.tokyometro.jp/unkou/index.html",
        },
      ],
      alternativeStations: [
        {
          stationName: "都営浅草線 浅草駅",
          stationCode: "A18",
          operatorName: "東京都交通局",
          stationPageUrl: "https://www.kotsu.metro.tokyo.jp/subway/stations/asakusa.html",
          mapQuery: "都営浅草線 浅草駅 東京都台東区駒形1-12-14",
        },
        {
          stationName: "東武スカイツリーライン 浅草駅",
          stationCode: "",
          operatorName: "東武鉄道",
          stationPageUrl: "https://www.tobu.co.jp/railway/guide/station/info/1102.html",
          mapQuery: "東武鉄道 浅草駅 東京都台東区花川戸1丁目",
        },
        {
          stationName: "つくばエクスプレス 浅草駅",
          stationCode: "TX03",
          operatorName: "つくばエクスプレス",
          stationPageUrl: "https://www.mir.co.jp/route_map/asakusa/",
          mapQuery: "つくばエクスプレス 浅草駅 東京都台東区西浅草3-1-11",
        },
      ],
    },
    {
      id: "asakusa-return",
      courseId: "asakusa-history",
      role: "return",
      roleLabel: "帰り",
      stationName: "田原町駅",
      stationCode: "G18",
      routeConnection: "コースGOALが田原町駅です。",
      recommendedExit: "",
      exitVerified: false,
      mapQuery: "東京メトロ 田原町駅 東京都台東区西浅草1-1-18",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      officialSources: [
        { label: "東京メトロ 田原町駅", url: "https://www.tokyometro.jp/station/tawaramachi/index.html" },
        { label: "東京メトロ 田原町駅バリアフリー設備", url: "https://www.tokyometro.jp/station/tawaramachi/accessibility/index.html" },
      ],
      operators: [
        {
          name: "東京メトロ",
          lines: ["銀座線"],
          stationPageUrl: "https://www.tokyometro.jp/station/tawaramachi/index.html",
          timetableUrl: "https://www.tokyometro.jp/station/tawaramachi/timetable/index.html",
          stationMapUrl: "https://www.tokyometro.jp/station/tawaramachi/index.html",
          barrierFreeUrl: "https://www.tokyometro.jp/station/tawaramachi/accessibility/index.html",
          operationInfoUrl: "https://www.tokyometro.jp/unkou/index.html",
        },
      ],
      alternativeStations: [],
    },
  ],
  toilets: [
    {
      id: "koenji-kita-public-toilet",
      courseId: "koenji-first",
      areaId: "koenji",
      name: "高円寺北公衆便所",
      type: "public",
      routePart: "first",
      nearStopOrder: 3,
      nearStopName: "小杉湯",
      locationNote: "コース3番・小杉湯付近（高円寺北公園内）",
      address: "東京都杉並区高円寺北3-20-15",
      mapQuery: "高円寺北公衆便所 東京都杉並区高円寺北3-20-15",
      latitude: 35.707362,
      longitude: 139.648993,
      wheelchair: true,
      ostomate: false,
      infantFacilities: null,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "available",
      sourceName: "杉並区 公衆トイレ一覧",
      sourceUrl: "https://catalog.data.metro.tokyo.lg.jp/dataset/t131156d0000000206",
      officialUrl: "https://www.city.suginami.tokyo.jp/documents/1609/131156_public_toilet.csv",
      datasetUrl: "https://www.city.suginami.tokyo.jp/documents/1609/131156_public_toilet.csv",
      sourceLicense: "CC BY 4.0",
      sourceUpdatedAt: "2025-03",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "koenji-chuo-public-toilet",
      courseId: "koenji-first",
      areaId: "koenji",
      name: "高円寺中央公衆便所",
      type: "public",
      routePart: "second",
      nearStopOrder: 4,
      nearStopName: "高円寺氷川神社・気象神社",
      locationNote: "コース4番・高円寺氷川神社・気象神社付近（前半の終点・後半の出発地点）",
      address: "東京都杉並区高円寺南4-31-7",
      mapQuery: "高円寺中央公衆便所 東京都杉並区高円寺南4-31-7",
      latitude: 35.703719,
      longitude: 139.651715,
      wheelchair: true,
      ostomate: false,
      infantFacilities: null,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "available",
      sourceName: "杉並区 公衆トイレ一覧",
      sourceUrl: "https://catalog.data.metro.tokyo.lg.jp/dataset/t131156d0000000206",
      officialUrl: "https://www.city.suginami.tokyo.jp/s100/shisetsu/14703.html",
      datasetUrl: "https://www.city.suginami.tokyo.jp/documents/1609/131156_public_toilet.csv",
      sourceLicense: "CC BY 4.0",
      sourceUpdatedAt: "2025-03",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "konan-sho-park-toilet",
      courseId: "koenji-first",
      areaId: "koenji",
      name: "高南小公園トイレ",
      type: "park",
      routePart: "goal",
      nearStopOrder: 6,
      nearStopName: "高円寺ルック商店街",
      locationNote: "コース6番・高円寺ルック商店街付近（GOALへ向かう途中）",
      address: "東京都杉並区高円寺南2-47-7",
      mapQuery: "高南小公園トイレ 東京都杉並区高円寺南2-47-7",
      latitude: 35.702002,
      longitude: 139.648439,
      wheelchair: false,
      ostomate: false,
      infantFacilities: null,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "available",
      sourceName: "杉並区 公衆トイレ一覧",
      sourceUrl: "https://www.city.suginami.tokyo.jp/s100/1622.html",
      officialUrl: "https://www.city.suginami.tokyo.jp/s100/1622.html",
      datasetUrl: "https://www.city.suginami.tokyo.jp/documents/1609/131156_public_toilet.csv",
      sourceLicense: "CC BY 4.0",
      sourceUpdatedAt: "2025-03",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "kichijoji-south-exit-public-toilet",
      courseId: "kichijoji-park",
      areaId: "kichijoji",
      name: "吉祥寺駅南口公衆トイレ",
      type: "public",
      routePart: "start",
      nearStopOrder: 1,
      nearStopName: "吉祥寺駅公園口",
      locationNote: "START・コース1番の吉祥寺駅公園口から利用しやすい",
      address: "東京都武蔵野市吉祥寺南町2-2",
      mapQuery: "吉祥寺駅南口公衆トイレ 東京都武蔵野市吉祥寺南町2-2",
      latitude: null,
      longitude: null,
      wheelchair: true,
      ostomate: true,
      infantFacilities: true,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "available",
      sourceName: "武蔵野市 公衆トイレについて",
      sourceUrl: "https://www.city.musashino.lg.jp/gomi_kankyo/gomi/bunbetsu_kaishu_torikumi/event_gomisogotaisaku/1045612.html",
      officialUrl: "https://www.city.musashino.lg.jp/gomi_kankyo/gomi/bunbetsu_kaishu_torikumi/event_gomisogotaisaku/1045612.html",
      datasetUrl: "https://catalog.data.metro.tokyo.lg.jp/dataset/t132039d0000000005",
      sourceLicense: "CC BY 4.0",
      sourceUpdatedAt: "2025-12-12",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "nakamichi-park-seasonal-toilet",
      courseId: "kichijoji-park",
      areaId: "kichijoji",
      name: "中道公園 子ども用トイレ",
      type: "park",
      routePart: "second",
      nearStopOrder: 5,
      nearStopName: "中道通り",
      locationNote: "コース5番・中道通り付近（後半ルートで利用しやすい）",
      address: "東京都武蔵野市吉祥寺本町3-10",
      mapQuery: "中道公園 東京都武蔵野市吉祥寺本町3-10",
      latitude: 35.7156552861886,
      longitude: 139.57656620024,
      wheelchair: null,
      ostomate: null,
      infantFacilities: null,
      availableStartTime: "10:00",
      availableEndTime: "17:00",
      availableTimeNote: "夏季のみ（実施期間は公式情報で要確認）",
      usageNote: "子ども用トイレです。利用できる時期と当日の開放状況は現地表示をご確認ください。",
      status: "information-pending",
      sourceName: "武蔵野市 公園トイレ",
      sourceUrl: "https://www.city.musashino.lg.jp/shisetsu_annai/koen_shiminnouen/kichijouji_honcho/1000670.html",
      officialUrl: "https://www.city.musashino.lg.jp/shisetsu_annai/koen_shiminnouen/kichijouji_honcho/1000670.html",
      datasetUrl: "https://www.city.musashino.lg.jp/_res/common/opendata_kikaku/4_4_4kouen-toilet.csv",
      sourceLicense: "CC BY 4.0",
      sourceUpdatedAt: "2022-07-15",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "komagatabashi-public-toilet",
      courseId: "asakusa-history",
      areaId: "asakusa",
      name: "駒形橋際公衆トイレ",
      type: "public",
      routePart: "start",
      nearStopOrder: 1,
      nearStopName: "浅草文化観光センター",
      locationNote: "START・コース1番の浅草文化観光センター付近",
      address: "東京都台東区雷門2-1-1",
      mapQuery: "駒形橋際公衆トイレ 東京都台東区雷門2-1-1",
      latitude: null,
      longitude: null,
      wheelchair: null,
      ostomate: null,
      infantFacilities: null,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "information-pending",
      sourceName: "台東区 公衆・公園トイレリスト",
      sourceUrl: "https://www.city.taito.lg.jp/kenchiku/toshikeikaku/keikaku/toshikeikaku/shiryo.files/toshidukurinotamenokisosiryou_chapter5.pdf",
      officialUrl: "https://www.city.taito.lg.jp/kenchiku/toshikeikaku/keikaku/toshikeikaku/shiryo.files/toshidukurinotamenokisosiryou_chapter5.pdf",
      datasetUrl: "https://www.city.taito.lg.jp/kusei/online/opendata/seikatu/shisethutizujouhou.files/20250314_koshu_koen_toilet.csv",
      sourceLicense: "台東区 CC-BY表示4.0国際",
      sourceAttributionNote: "本作品の内容について、台東区は一切保証しないものとする。",
      sourceUpdatedAt: "2025-03-14",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "nakamise-4-public-toilet",
      courseId: "asakusa-history",
      areaId: "asakusa",
      name: "仲見世4号公衆トイレ",
      type: "public",
      routePart: "first",
      nearStopOrder: 4,
      nearStopName: "浅草寺",
      locationNote: "コース4番・浅草寺付近（前半ルートで利用しやすい）",
      address: "東京都台東区浅草1-37-2",
      mapQuery: "仲見世4号公衆トイレ 東京都台東区浅草1-37-2",
      latitude: null,
      longitude: null,
      wheelchair: null,
      ostomate: null,
      infantFacilities: null,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "information-pending",
      sourceName: "台東区 公衆・公園トイレリスト",
      sourceUrl: "https://www.city.taito.lg.jp/kenchiku/toshikeikaku/keikaku/toshikeikaku/shiryo.files/toshidukurinotamenokisosiryou_chapter5.pdf",
      officialUrl: "https://www.city.taito.lg.jp/kenchiku/toshikeikaku/keikaku/toshikeikaku/shiryo.files/toshidukurinotamenokisosiryou_chapter5.pdf",
      datasetUrl: "https://www.city.taito.lg.jp/kusei/online/opendata/seikatu/shisethutizujouhou.files/20250314_koshu_koen_toilet.csv",
      sourceLicense: "台東区 CC-BY表示4.0国際",
      sourceAttributionNote: "本作品の内容について、台東区は一切保証しないものとする。",
      sourceUpdatedAt: "2025-03-14",
      informationCheckedAt: "2026-07-28",
    },
    {
      id: "tawaramachi-public-toilet",
      courseId: "asakusa-history",
      areaId: "asakusa",
      name: "田原町交番裏公衆トイレ",
      type: "public",
      routePart: "second",
      nearStopOrder: 8,
      nearStopName: "田原町駅",
      locationNote: "GOAL・コース8番の田原町駅付近（後半ルートで利用しやすい）",
      address: "東京都台東区西浅草1-8-11",
      mapQuery: "田原町交番裏公衆トイレ 東京都台東区西浅草1-8-11",
      latitude: null,
      longitude: null,
      wheelchair: null,
      ostomate: null,
      infantFacilities: null,
      availableStartTime: "",
      availableEndTime: "",
      availableTimeNote: "",
      usageNote: "",
      status: "information-pending",
      sourceName: "台東区 公衆・公園トイレリスト",
      sourceUrl: "https://www.city.taito.lg.jp/kenchiku/toshikeikaku/keikaku/toshikeikaku/shiryo.files/toshidukurinotamenokisosiryou_chapter5.pdf",
      officialUrl: "https://www.city.taito.lg.jp/kenchiku/toshikeikaku/keikaku/toshikeikaku/shiryo.files/toshidukurinotamenokisosiryou_chapter5.pdf",
      datasetUrl: "https://www.city.taito.lg.jp/kusei/online/opendata/seikatu/shisethutizujouhou.files/20250314_koshu_koen_toilet.csv",
      sourceLicense: "台東区 CC-BY表示4.0国際",
      sourceAttributionNote: "本作品の内容について、台東区は一切保証しないものとする。",
      sourceUpdatedAt: "2025-03-14",
      informationCheckedAt: "2026-07-28",
    },
  ],
  foodBreaks: [
    {
      id: "koenji-suzuya",
      courseId: "koenji-first",
      areaId: "koenji",
      name: "すず舎",
      category: "うどん",
      role: "meal",
      roleLabel: "食事",
      routePart: "first",
      nearStopOrder: 2,
      nearStopName: "高円寺純情商店街",
      locationNote: "コース2番付近",
      address: "東京都杉並区高円寺北2-20-6",
      editorialNote: "前半ルートで食事を取りたい場合に検討できる候補です。",
      mapQuery: "すず舎 東京都杉並区高円寺北2-20-6",
      officialUrl: "https://www.kouenji.or.jp/shop/food/suzuya.html",
      menuUrl: "",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1319/A131904/13316948/",
      servicePeriods: ["lunch", "dinner"],
      priceLabel: "公式情報をご確認ください",
      priceSourceUrl: "",
      takeout: null,
      reservation: null,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "高円寺純情商店街 公式店舗ページ",
      sourceUrl: "https://www.kouenji.or.jp/shop/food/suzuya.html",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "koenji-trianon",
      courseId: "koenji-first",
      areaId: "koenji",
      name: "トリアノン洋菓子店 高円寺本店",
      category: "洋菓子・喫茶",
      role: "takeout",
      roleLabel: "テイクアウト",
      routePart: "second",
      nearStopOrder: 4,
      nearStopName: "高円寺氷川神社・気象神社",
      locationNote: "コース4番付近",
      address: "東京都杉並区高円寺南4-26-12",
      editorialNote: "前半から後半へ移る地点付近で、洋菓子の持ち帰りや喫茶利用を検討できます。",
      mapQuery: "トリアノン洋菓子店 高円寺本店 東京都杉並区高円寺南4-26-12",
      officialUrl: "https://trianon.co.jp/shop/",
      menuUrl: "https://trianon.co.jp/menu/",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1319/A131904/13006597/",
      servicePeriods: ["cafe", "takeout"],
      priceLabel: "公式メニューをご確認ください",
      priceSourceUrl: "https://trianon.co.jp/menu/",
      takeout: true,
      reservation: null,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "トリアノン洋菓子店 公式サイト",
      sourceUrl: "https://trianon.co.jp/shop/",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "koenji-doutor-shin-koenji",
      courseId: "koenji-first",
      areaId: "koenji",
      name: "ドトールコーヒーショップ 新高円寺店",
      category: "カフェ",
      role: "cafe-break",
      roleLabel: "カフェ休憩",
      routePart: "goal",
      nearStopOrder: 7,
      nearStopName: "新高円寺駅",
      locationNote: "GOAL・コース7番付近",
      address: "東京都杉並区梅里2-1-17",
      editorialNote: "GOAL付近でカフェ休憩を取りたい場合に検討できる候補です。",
      mapQuery: "ドトールコーヒーショップ 新高円寺店 東京都杉並区梅里2-1-17",
      officialUrl: "https://shop.doutor.co.jp/doutor/spot/detail?code=1010455",
      menuUrl: "https://www.doutor.co.jp/dcs/menu/",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1319/A131904/13086811/",
      servicePeriods: ["breakfast", "lunch", "cafe"],
      priceLabel: "公式メニューをご確認ください",
      priceSourceUrl: "https://www.doutor.co.jp/dcs/menu/",
      takeout: null,
      reservation: null,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "ドトールコーヒー 公式店舗ページ",
      sourceUrl: "https://shop.doutor.co.jp/doutor/spot/detail?code=1010455",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "kichijoji-chai-break",
      courseId: "kichijoji-park",
      areaId: "kichijoji",
      name: "chai break",
      category: "紅茶・チャイ",
      role: "cafe-break",
      roleLabel: "カフェ休憩",
      routePart: "first",
      nearStopOrder: 1,
      nearStopName: "吉祥寺駅公園口",
      locationNote: "START・コース1番付近",
      address: "東京都武蔵野市御殿山1-3-2",
      editorialNote: "公園へ向かう前半ルートで、紅茶やチャイの休憩を検討できる候補です。",
      mapQuery: "chai break 東京都武蔵野市御殿山1-3-2",
      officialUrl: "https://www.chai-break.com/",
      menuUrl: "",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1320/A132001/13098849/",
      servicePeriods: ["breakfast", "cafe"],
      priceLabel: "公式情報をご確認ください",
      priceSourceUrl: "",
      takeout: null,
      reservation: null,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "chai break 公式サイト",
      sourceUrl: "https://www.chai-break.com/",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "kichijoji-pepacafe-forest",
      courseId: "kichijoji-park",
      areaId: "kichijoji",
      name: "ペパカフェ・フォレスト",
      category: "タイ・ベトナム料理",
      role: "meal",
      roleLabel: "食事",
      routePart: "first",
      nearStopOrder: 2,
      nearStopName: "七井橋",
      locationNote: "コース2番付近・井の頭公園内",
      address: "東京都三鷹市井の頭4-1-5",
      editorialNote: "井の頭公園を歩く前半で、食事を取りたい場合に検討できる候補です。",
      mapQuery: "ペパカフェ フォレスト 東京都三鷹市井の頭4-1-5",
      officialUrl: "https://www.instagram.com/pepacafe_forest/",
      menuUrl: "",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1320/A132001/13005873/",
      servicePeriods: ["lunch", "dinner"],
      priceLabel: "公式情報をご確認ください",
      priceSourceUrl: "",
      takeout: null,
      reservation: true,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "ペパカフェ・フォレスト 公式Instagram",
      sourceUrl: "https://www.instagram.com/pepacafe_forest/",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "kichijoji-tsukada-suisan",
      courseId: "kichijoji-park",
      areaId: "kichijoji",
      name: "塚田水産",
      category: "さつま揚げ・おでん種",
      role: "takeout",
      roleLabel: "テイクアウト",
      routePart: "goal",
      nearStopOrder: 7,
      nearStopName: "ハモニカ横丁",
      locationNote: "GOAL・コース7番付近",
      address: "東京都武蔵野市吉祥寺本町1-1-8",
      editorialNote: "GOAL付近で持ち帰りを検討できる、公式店舗情報のある候補です。",
      mapQuery: "塚田水産 東京都武蔵野市吉祥寺本町1-1-8",
      officialUrl: "https://tsukada-satsuma.com/",
      menuUrl: "https://tsukada-satsuma.com/",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1320/A132001/13098318/",
      servicePeriods: ["takeout"],
      priceLabel: "公式ラインナップをご確認ください",
      priceSourceUrl: "https://tsukada-satsuma.com/",
      takeout: true,
      reservation: false,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "塚田水産 公式サイト",
      sourceUrl: "https://tsukada-satsuma.com/",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "asakusa-funawa-cafe",
      courseId: "asakusa-history",
      areaId: "asakusa",
      name: "ふなわかふぇ 浅草店",
      category: "甘味・カフェ",
      role: "short-break",
      roleLabel: "ひと休み",
      routePart: "start",
      nearStopOrder: 1,
      nearStopName: "浅草文化観光センター",
      locationNote: "START・コース1番付近",
      address: "東京都台東区雷門2-19-10",
      editorialNote: "散歩を始める前や雷門付近で、短い休憩を検討できる候補です。",
      mapQuery: "ふなわかふぇ 浅草店 東京都台東区雷門2-19-10",
      officialUrl: "https://funawa.jp/fr/40",
      menuUrl: "https://funawa.jp/fr/69",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1311/A131102/13153011/",
      servicePeriods: ["cafe", "takeout"],
      priceLabel: "公式メニューをご確認ください",
      priceSourceUrl: "https://funawa.jp/fr/69",
      takeout: true,
      reservation: false,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "舟和 公式サイト",
      sourceUrl: "https://funawa.jp/fr/40",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "asakusa-mugitoro",
      courseId: "asakusa-history",
      areaId: "asakusa",
      name: "浅草むぎとろ 本店",
      category: "とろろ料理・日本料理",
      role: "meal",
      roleLabel: "食事",
      routePart: "first",
      nearStopOrder: 2,
      nearStopName: "雷門",
      locationNote: "コース2番付近",
      address: "東京都台東区雷門2-2-4",
      editorialNote: "前半ルートで食事を取りたい場合に検討できる、公式情報のある候補です。",
      mapQuery: "浅草むぎとろ 本店 東京都台東区雷門2-2-4",
      officialUrl: "https://www.mugitoro.co.jp/",
      menuUrl: "https://www.mugitoro.co.jp/",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1311/A131102/13003680/",
      servicePeriods: ["lunch", "dinner"],
      priceLabel: "公式メニューをご確認ください",
      priceSourceUrl: "https://www.mugitoro.co.jp/",
      takeout: null,
      reservation: true,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "浅草むぎとろ 公式サイト",
      sourceUrl: "https://www.mugitoro.co.jp/",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
    {
      id: "asakusa-pelican-cafe",
      courseId: "asakusa-history",
      areaId: "asakusa",
      name: "ペリカンカフェ",
      category: "カフェ・サンドイッチ",
      role: "cafe-break",
      roleLabel: "カフェ休憩",
      routePart: "goal",
      nearStopOrder: 8,
      nearStopName: "田原町駅",
      locationNote: "GOAL・コース8番付近",
      address: "東京都台東区寿3-9-11",
      editorialNote: "かっぱ橋からGOALへ向かう後半で、カフェ休憩を検討できる候補です。",
      mapQuery: "ペリカンカフェ 東京都台東区寿3-9-11",
      officialUrl: "https://pelicancafe.jp/",
      menuUrl: "https://pelicancafe.jp/",
      reservationUrl: "",
      tabelogUrl: "https://tabelog.com/tokyo/A1311/A131103/13212182/",
      servicePeriods: ["breakfast", "lunch", "cafe"],
      priceLabel: "公式メニューをご確認ください",
      priceSourceUrl: "https://pelicancafe.jp/",
      takeout: null,
      reservation: null,
      vegetarian: null,
      vegan: null,
      halal: null,
      accessibilityNote: "",
      status: "available",
      sourceName: "ペリカンカフェ 公式サイト",
      sourceUrl: "https://pelicancafe.jp/",
      informationCheckedAt: "2026-07-28",
      fieldResearch: false,
      isSponsored: false,
    },
  ],
  spots: [
    {
      id: "koenji-junjo",
      areaId: "koenji",
      name: "高円寺純情商店街",
      category: "商店街",
      excerpt: "高円寺駅北口から始まる商店街。北側散歩の導入として歩きやすい場所です。",
      image: "spotKoenjiJunjo",
      imageAlt: "高円寺の低層商店街と路地を表現したイメージ",
      mapQuery: "高円寺純情商店街",
      officialUrl: "https://www.kouenji.or.jp/",
    },
    {
      id: "koenji-hikawa",
      areaId: "koenji",
      name: "高円寺氷川神社・気象神社",
      category: "神社",
      excerpt: "高円寺駅南側で、商店街歩きに歴史の立ち寄りを加えられる場所です。",
      image: "spotKoenjiHikawa",
      imageAlt: "高円寺氷川神社・気象神社の鳥居と境内を表現したイメージ",
      mapQuery: "高円寺氷川神社 気象神社",
      officialUrl: "https://koenji-hikawa.com/",
    },
    {
      id: "inokashira-park",
      areaId: "kichijoji",
      name: "井の頭恩賜公園",
      category: "公園",
      excerpt: "池、水辺、木陰を楽しめる吉祥寺散歩の中心。短時間でも景色を変えやすい公園です。",
      image: "spotInokashiraPark",
      imageAlt: "井の頭恩賜公園の緑と水辺を表現したイメージ",
      mapQuery: "井の頭恩賜公園",
      officialUrl: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/",
    },
    {
      id: "kichijoji-art-museum",
      areaId: "kichijoji",
      name: "武蔵野市立吉祥寺美術館",
      category: "文化施設",
      excerpt: "駅近くで雨天時にも組み込みやすい文化施設。商店街散歩の休憩地点にもなります。",
      image: "spotKichijojiArtMuseum",
      imageAlt: "吉祥寺の街中にある都市型美術館を表現したイメージ",
      mapQuery: "武蔵野市立吉祥寺美術館",
      officialUrl: "https://www.musashino.or.jp/museum/",
    },
    {
      id: "sensoji",
      areaId: "asakusa",
      name: "浅草寺周辺",
      category: "寺社・歴史",
      excerpt: "浅草の歴史散歩の中心。朝と昼で人の流れが大きく変わるため、時間帯選びも楽しみの一つです。",
      image: "spotSensoji",
      imageAlt: "浅草寺周辺の門前町と寺院建築を表現したイメージ",
      mapQuery: "浅草寺",
      officialUrl: "https://www.senso-ji.jp/",
    },
    {
      id: "kappabashi",
      areaId: "asakusa",
      name: "かっぱ橋道具街",
      category: "商店街",
      excerpt: "調理道具や器の専門店が続く通り。浅草寺周辺から少し歩くことで街の表情が変わります。",
      image: "spotKappabashi",
      imageAlt: "かっぱ橋道具街の調理器具店が並ぶ通りを表現したイメージ",
      mapQuery: "かっぱ橋道具街",
      officialUrl: "https://www.kappabashi.or.jp/",
    },
  ],
  stories: [
    {
      id: "koenji-shopping-streets",
      areaId: "koenji",
      category: "街の読み物",
      readTime: "約4分",
      title: "高円寺は、商店街を一本に決めないほうが面白い。",
      excerpt: "純情商店街からパル、ルックへ。駅の北と南をつなぐと、買い物の街と生活の街が同時に見えてきます。",
      image: "storyKoenjiShoppingStreets",
      imageAlt: "高円寺の複数の商店街と路地を歩き継ぐ読み物を表現したイメージ",
      intro: "高円寺の面白さは、一つの有名スポットを目指すことより、商店街の切り替わりを歩いて確かめることにあります。",
      sections: [
        { heading: "北口は、散歩の速度を落としやすい", body: "駅を出て純情商店街へ入ると、飲食店や生活に近い店が短い間隔で並びます。目的を一つに絞らず、気になった通りを一本だけ横へ入るのが向いています。" },
        { heading: "南口では、アーケードが街をつなぐ", body: "氷川神社を経由して南へ回ると、パル商店街とルック商店街が連続します。雨や強い日差しを避けながら歩きやすい区間です。" },
        { heading: "二つの駅を結ぶと、帰り方も選べる", body: "高円寺駅へ戻るだけでなく、新高円寺駅をゴールにすると同じ道を引き返さずに済みます。体力に合わせて途中で地下鉄へ切り替えられるのも利点です。" },
      ],
    },
    {
      id: "inokashira-short-walk",
      areaId: "kichijoji",
      category: "公園の読み物",
      readTime: "約4分",
      title: "井の頭公園は、一周しなくても十分に深い。",
      excerpt: "七井橋、井の頭池、弁財天。駅から近い公園を「短く歩いて、長く眺める」半日へ。",
      image: "storyInokashiraShortWalk",
      imageAlt: "井の頭公園の橋、水辺、木陰を短く巡る読み物を表現したイメージ",
      intro: "井の頭公園は広いからこそ、全部を見るより、橋・水辺・木陰を一つずつ選ぶ方が満足しやすい場所です。",
      sections: [
        { heading: "最初に七井橋で景色をつかむ", body: "公園へ下りたら、まず橋の上から池の広がりを確認します。歩く範囲を決める目印にもなります。" },
        { heading: "池を一周しない選択", body: "混雑や暑さが気になる日は、弁財天周辺までに絞り、木陰で過ごす時間を増やすのがおすすめです。" },
        { heading: "街へ戻る道も散歩に含める", body: "御殿山や中道通りを経由すれば、公園の緑から小さな店が続く街へ自然に切り替わります。" },
      ],
    },
    {
      id: "asakusa-first-hour",
      areaId: "asakusa",
      category: "街の読み物",
      readTime: "約4分",
      title: "浅草の最初の1時間は、雷門の向かいから始める。",
      excerpt: "浅草文化観光センターで、地図、混雑、休憩場所を確認してから門前町へ入る。",
      image: "storyAsakusaFirstHour",
      imageAlt: "浅草の街を見渡してから門前町へ入る読み物を表現したイメージ",
      intro: "浅草は最初から人の流れに乗るより、少し高い場所から街の方向を確認すると歩きやすくなります。",
      sections: [
        { heading: "最初に情報を集める", body: "浅草文化観光センターで地図や当日の案内を確認しておくと、雷門周辺の混雑に合わせて進路を変えやすくなります。" },
        { heading: "仲見世は目的地ではなく通過点", body: "仲見世を抜けて浅草寺へ進んだ後、西側の通りへ回ると、門前町の異なる表情が見えてきます。" },
        { heading: "最後は道具街へ", body: "かっぱ橋まで歩くと、寺社中心の景色から専門店の街へ変化します。田原町駅をゴールにすれば帰路も分かりやすくなります。" },
      ],
    },
  ],
  events: [
    {
      id: "kagurazaka-festival-2026",
      title: "第52回 神楽坂まつり",
      area: "神楽坂",
      start: "2026-07-22T17:00:00+09:00",
      end: "2026-07-25T21:00:00+09:00",
      venue: "神楽坂通り周辺",
      price: "観覧無料",
      status: "",
      image: "eventKagurazakaFestival",
      imageAlt: "提灯と屋台が並ぶ神楽坂の夏祭りを表現したイメージ",
      officialUrl: "https://www.kagurazaka.in/kagurazaka_festival/52th/",
      mapQuery: "神楽坂通り",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
    {
      id: "shinjuku-eisa-2026",
      title: "第23回 新宿エイサーまつり",
      area: "新宿",
      start: "2026-07-25T12:00:00+09:00",
      end: "2026-07-25T20:00:00+09:00",
      venue: "新宿駅東口周辺",
      price: "観覧無料",
      status: "",
      image: "eventShinjukuEisa",
      imageAlt: "新宿の街路で行われるエイサー演舞を表現したイメージ",
      officialUrl: "https://www.shinjuku-eisa.com/",
      mapQuery: "新宿駅 東口",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
    {
      id: "sumidagawa-fireworks-2026",
      title: "第49回 隅田川花火大会",
      area: "浅草・墨田",
      start: "2026-07-25T19:00:00+09:00",
      end: "2026-07-25T20:30:00+09:00",
      venue: "隅田川 第一・第二会場",
      price: "観覧無料（一部有料席）",
      status: "",
      image: "eventSumidagawaFireworks",
      imageAlt: "隅田川の水面と夜空の花火を表現したイメージ",
      officialUrl: "https://www.sumidagawa-hanabi.com/",
      mapQuery: "隅田川花火大会 第一会場",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
    {
      id: "koganei-awaodori-2026",
      title: "第48回 小金井阿波おどり",
      area: "小金井",
      start: "2026-07-25T18:00:00+09:00",
      end: "2026-07-26T21:00:00+09:00",
      venue: "武蔵小金井駅周辺",
      price: "観覧無料",
      status: "",
      image: "eventKoganeiAwaodori",
      imageAlt: "武蔵小金井駅周辺の阿波おどりを表現したイメージ",
      officialUrl: "https://koganeiawaodori.jp/",
      mapQuery: "武蔵小金井駅",
      informationCheckedAt: "",
      lastUpdated: "2026-07-22",
    },
  ],
};
